# docker-compose.yml

version: "3.9"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - addressbook-db:/data/db
    ports:
      - '27017:27017'

  addressbook:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - mongo
    ports:
      - '3000:3000'
        
volumes:
  addressbook-db: